general.import = [ "~/.config/omarchy/current/theme/alacritty.toml" ]

[env]
TERM = "xterm-256color"

[font]
normal = { family = "JetBrainsMono Nerd Font" }
bold = { family = "JetBrainsMono Nerd Font" }
italic = { family = "JetBrainsMono Nerd Font" }
size = 9

[window]
padding.x = 14
padding.y = 14
decorations = "None"

[keyboard]
bindings = [
{ key = "Insert", mods = "Shift", action = "Paste" },
{ key = "Insert", mods = "Control", action = "Copy" },
# Ny mappning: Ctrl + Backspace skickar ^W (raderar föregående ord)
    { key = "Back", mods = "Control", chars = "\u0017" }
]

################ ADD THIS PART #############
[terminal.shell]
program = "/home/linuxbrew/.linuxbrew/bin/nu"
# args = ["-l"]
############################################





